apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: py-tt-yy-ghruty
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: py-tt-yy-ghruty 
  name: py-tt-yy-ghruty
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: py-tt-yy-ghruty 
